import Head from "next/head";

import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai"
import Image from "next/image";
import deved from '/public/Aman4.png'
import help from "/public/help2.png"
import velp from "/public/help3.png"
import workshop from "/public/brandin.png"
import web1 from "/public/web6.png"
import web2 from "/public/web1.png"
import web3 from "/public/web5.png"
import web4 from "/public/web2.png"
import web5 from "/public/web1.png"
import web from "/public/web4.png"


import { useState } from "react"


  export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
  return (
    <div className ={darkMode ? 'dark' : ""}>
      <Head>
        <title>Aman Velpula Portfolio</title>
        <meta name = "description" content = "Generated by cre"></meta>
        <link rel = "icon" href = "/favicon.ico"></link>
      </Head>

      <main className ="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className = "p-10 mb-12 flex justify-between">
            <h1 className ="text-4xl font-semibold dark:text-white">Velp</h1>
            <ul className = "flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className = "cursor-pointer text-2xl dark:text-white"/>
              </li>
              <li><a className = "bg-gradient-to-r from-red-300 to-red-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className = "text-center p-10 dark:text-white">
            <h2 className ="text-5xl py2 text-red-400 font-medium">Aman Velp</h2>
            <h3 className = "text-2xl py-2">Frontend Developer and fulltime doodler.</h3>
            <p className = "text-md py-5 leading-8 text-gray-800 dark:text-white">I'm a university student studying Computer Science that has a passion for
              building, learning & fitness. Find out more about me!
            </p>
          </div>
          <div className = "text-5xl flex justify-center gap-16 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className = "relative mx-auto bg-gradient-to-b from-red-300 rounded-full w-80 h-80 mt-10 overflow-hidden">
            <Image src={deved} layout ="fill" objectFit = "cover"/>
          </div>

        </section>

        <section>
        <div>
          <h3 className = "text-4xl font-semibold py-1">Services I <span className = "text-red-500">provide..</span></h3>
          <p className = "text-md py-2 leading-8 text-gray-80">Since I start off with web development I've been immersed in creating applications that serve a purpose. Contact me and I will create an amazing website for you that is functional
            and well maintained. I also offer  <span className = "text-red-400">coaching</span> services where I'll <span className = "text-red-400">teach</span> you essential skills needed.
          </p>
          <p className = "text-md py-2 leading-8 text-gray-80"> I offer a wide range of services including brand design, programming, web design & coaching.
          </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <div className="flex justify-center">
              <Image src={velp} width={150} height={150} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <div className="flex justify-center">
              <Image src={workshop} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Branding Help
              </h3>
              <p className="py-2">
                Helping you kickstart your personal brand using various tools & methodologies for social media growth.
              </p>
              <h4 className="py-4 text-teal-600">Branding Tools I Use</h4>
              <p className="text-gray-800 py-1">Hypefury</p>
              <p className="text-gray-800 py-1">Twitter</p>
              <p className="text-gray-800 py-1">Linkedln</p>
              <p className="text-gray-800 py-1">Doordash</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <div className="flex justify-center">
              <Image src={help} width={150} height={150} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Development Coaching
              </h3>
              <p className="py-2">
                Coaching you to become the best Frontend developer in the market. Getting you job ready & project building ready.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools I Use</h4>
              <p className="text-gray-800 py-1">VScode</p>
              <p className="text-gray-800 py-1">React/JavaScript</p>
              <p className="text-gray-800 py-1">ChatGpt</p>
              <p className="text-gray-800 py-1">Tailwind</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
